set_property SRC_FILE_INFO {cfile:/home1/shivang/github/HMB_CalRDout/HMB_Cal/HMB_Cal.srcs/constrs_1/new/Target_c_basic.xdc rfile:../../../HMB_Cal.srcs/constrs_1/new/Target_c_basic.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE none [get_ports unused_port_name]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R19 [get_ports A_TRIG1]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T11 [get_ports MONTIMING_P]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T10 [get_ports MONTIMING_N]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U13 [get_ports A_RAMP]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V13 [get_ports A_SS_LD_DIR]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T14 [get_ports A_SS_LD_SIN]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T15 [get_ports A_SS_RESET]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports A_DONE]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y17 [get_ports A_DO_1]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T16 [get_ports A_DO_2]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U17 [get_ports A_DO_3]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U14 [get_ports A_DO_4]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U15 [get_ports A_DO_5]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18 [get_ports A_DO_6]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P19 [get_ports A_DO_7]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T20 [get_ports A_DO_8]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U20 [get_ports A_SS_INCR]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y18 [get_ports A_DO_9]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y19 [get_ports A_DO_10]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R16 [get_ports A_DO_11]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R17 [get_ports A_DO_12]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports A_DO_13]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V18 [get_ports A_DO_14]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N17 [get_ports A_DO_15]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P18 [get_ports A_DO_16]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7 [get_ports A_SAMPLESEL_ANY]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7 [get_ports A_RDAD_DIR]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8 [get_ports A_RDAD_SIN]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W8 [get_ports A_RDAD_CLK]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T19 [get_ports SIN]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P14 [get_ports SCLK]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R14 [get_ports A_PCLK]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W14 [get_ports A_SHOUT]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y14 [get_ports A_TRIG4]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N20 [get_ports A_TRIG3]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P20 [get_ports A_TRIG2]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W20 [get_ports A_WR_RS_S0]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports A_WR_RS_S1]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports A_WR_CS_S0]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P15 [get_ports A_WR_CS_S1]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16 [get_ports A_WR_CS_S2]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T9 [get_ports A_WR_CS_S3]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U10 [get_ports A_WR_CS_S4]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T5 [get_ports A_WR_CS_S5]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U5 [get_ports A_GCC_RESET]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports B_TRIG3]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C20 [get_ports B_TRIG2]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B20 [get_ports B_TRIG1]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E17 [get_ports B_RAMP]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports B_SS_LD_DIR]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E18 [get_ports B_SS_LD_SIN]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports B_SS_RESET]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L19 [get_ports B_DONE]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L20 [get_ports {B_DO_1[0]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports {B_DO_2[0]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports {B_DO_3[0]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y12 [get_ports {B_DO_4[0]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y13 [get_ports {B_DO_5[0]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V6 [get_ports {B_DO_6[0]}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W6 [get_ports {B_DO_7[0]}]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports B_TRIG4]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B19 [get_ports B_HSCLK_P]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20 [get_ports B_HSCLK_N]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D19 [get_ports B_PCLK]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D20 [get_ports B_SHOUT]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F16 [get_ports B_WR_RS_S0]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17 [get_ports B_WR_RS_S1]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M19 [get_ports B_WR_CS_S0]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M20 [get_ports B_WR_CS_S1]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K19 [get_ports B_WR_CS_S2]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J19 [get_ports B_WR_CS_S3]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports B_WR_CS_S4]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K18 [get_ports B_WR_CS_S5]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18 [get_ports B_GCC_RESET]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports B_RDAD_CLK]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F19 [get_ports B_RDAD_SIN]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F20 [get_ports B_RDAD_DIR]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J20 [get_ports B_SAMPLESEL_ANY]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H20 [get_ports {B_DO_16[0]}]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports {B_DO_15[0]}]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports {B_DO_14[0]}]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports {B_DO_13[0]}]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports {B_DO_12[0]}]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K16 [get_ports {B_DO_11[0]}]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J16 [get_ports {B_DO_10[0]}]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V11 [get_ports {B_DO_9[0]}]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V10 [get_ports B_SS_INCR]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports {B_DO_8[0]}]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_TRIG1]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports MONTIMING_P]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports MONTIMING_N]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_RAMP]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_SS_LD_DIR]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_SS_LD_SIN]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_SS_RESET]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_DONE]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_DO_1]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_DO_2]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_DO_3]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_DO_4]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_DO_5]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_DO_6]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_DO_7]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_DO_8]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_SS_INCR]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_DO_9]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_DO_10]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_DO_11]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_DO_12]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_DO_13]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_DO_14]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_DO_15]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_DO_16]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_SAMPLESEL_ANY]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_RDAD_DIR]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_RDAD_SIN]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_RDAD_CLK]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports SIN]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {SSTIN_P[0]}]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {SSTIN_N[0]}]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T12 [get_ports {SSTIN_P[0]}]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U12 [get_ports {SSTIN_N[0]}]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {WL_CLK_P[0]}]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {WL_CLK_N[0]}]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports {WL_CLK_P[0]}]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W13 [get_ports {WL_CLK_N[0]}]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports SCLK]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_PCLK]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_SHOUT]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_TRIG4]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports A_HSCLK_P]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports A_HSCLK_N]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V15 [get_ports A_HSCLK_P]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W15 [get_ports A_HSCLK_N]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_TRIG3]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_TRIG2]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_WR_RS_S0]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_WR_RS_S1]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_WR_CS_S0]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_WR_CS_S1]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_WR_CS_S2]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_WR_CS_S3]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_WR_CS_S4]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_WR_CS_S5]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports A_GCC_RESET]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_TRIG3]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_TRIG2]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_TRIG1]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_RAMP]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_SS_LD_DIR]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_SS_LD_SIN]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_SS_RESET]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_DONE]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {B_DO_1[0]}]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {B_DO_2[0]}]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {B_DO_3[0]}]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {B_DO_4[0]}]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {B_DO_5[0]}]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {B_DO_6[0]}]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {B_DO_7[0]}]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_TRIG4]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports B_HSCLK_P]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports B_HSCLK_N]
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_PCLK]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_SHOUT]
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_WR_RS_S0]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_WR_RS_S1]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_WR_CS_S0]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_WR_CS_S1]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_WR_CS_S2]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_WR_CS_S3]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_WR_CS_S4]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_WR_CS_S5]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_GCC_RESET]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_RDAD_CLK]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_RDAD_SIN]
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_RDAD_DIR]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_SAMPLESEL_ANY]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {B_DO_16[0]}]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {B_DO_15[0]}]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {B_DO_14[0]}]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {B_DO_13[0]}]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {B_DO_12[0]}]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {B_DO_11[0]}]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {B_DO_10[0]}]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {B_DO_9[0]}]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports B_SS_INCR]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {B_DO_8[0]}]
set_property src_info {type:XDC file:1 line:313 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[0]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[1]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[2]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[3]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[4]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[5]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[6]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[7]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[8]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[9]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[10]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[11]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[12]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[13]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[14]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[15]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[16]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[17]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[18]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[19]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[20]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[21]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[22]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[23]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[24]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[25]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[26]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[27]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[28]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[29]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[30]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/fifodata_intl[31]}]]
set_property src_info {type:XDC file:1 line:329 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/GEN_FIFO[0].FIFOCH/din[0]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/GEN_FIFO[0].FIFOCH/din[1]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/GEN_FIFO[0].FIFOCH/din[2]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/GEN_FIFO[0].FIFOCH/din[3]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/GEN_FIFO[0].FIFOCH/din[4]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/GEN_FIFO[0].FIFOCH/din[5]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/GEN_FIFO[0].FIFOCH/din[6]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/GEN_FIFO[0].FIFOCH/din[7]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/GEN_FIFO[0].FIFOCH/din[8]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/GEN_FIFO[0].FIFOCH/din[9]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/GEN_FIFO[0].FIFOCH/din[10]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/GEN_FIFO[0].FIFOCH/din[11]}]]
set_property src_info {type:XDC file:1 line:330 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/GEN_FIFO[0].FIFOCH/full}]]
set_property src_info {type:XDC file:1 line:333 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/fifo_rd_stm[0]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/fifo_rd_stm[1]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/fifo_rd_stm[2]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/fifo_rd_stm[3]}]]
set_property src_info {type:XDC file:1 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[16]}]
set_property src_info {type:XDC file:1 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[17]}]
set_property src_info {type:XDC file:1 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[18]}]
set_property src_info {type:XDC file:1 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[30]}]
set_property src_info {type:XDC file:1 line:341 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[31]}]
set_property src_info {type:XDC file:1 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[25]}]
set_property src_info {type:XDC file:1 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[28]}]
set_property src_info {type:XDC file:1 line:344 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[19]}]
set_property src_info {type:XDC file:1 line:345 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[20]}]
set_property src_info {type:XDC file:1 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[21]}]
set_property src_info {type:XDC file:1 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[27]}]
set_property src_info {type:XDC file:1 line:348 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[29]}]
set_property src_info {type:XDC file:1 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[22]}]
set_property src_info {type:XDC file:1 line:350 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[23]}]
set_property src_info {type:XDC file:1 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[26]}]
set_property src_info {type:XDC file:1 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[24]}]
set_property src_info {type:XDC file:1 line:353 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[1]}]
set_property src_info {type:XDC file:1 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[0]}]
set_property src_info {type:XDC file:1 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[2]}]
set_property src_info {type:XDC file:1 line:356 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[3]}]
set_property src_info {type:XDC file:1 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[4]}]
set_property src_info {type:XDC file:1 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[11]}]
set_property src_info {type:XDC file:1 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[5]}]
set_property src_info {type:XDC file:1 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[6]}]
set_property src_info {type:XDC file:1 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[7]}]
set_property src_info {type:XDC file:1 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[8]}]
set_property src_info {type:XDC file:1 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[14]}]
set_property src_info {type:XDC file:1 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[9]}]
set_property src_info {type:XDC file:1 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[12]}]
set_property src_info {type:XDC file:1 line:366 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[10]}]
set_property src_info {type:XDC file:1 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[15]}]
set_property src_info {type:XDC file:1 line:368 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_3_dout[13]}]
set_property src_info {type:XDC file:1 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_0_dout[0]}]
set_property src_info {type:XDC file:1 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_0_dout[1]}]
set_property src_info {type:XDC file:1 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_0_dout[2]}]
set_property src_info {type:XDC file:1 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_0_dout[3]}]
set_property src_info {type:XDC file:1 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_0_dout[4]}]
set_property src_info {type:XDC file:1 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_0_dout[5]}]
set_property src_info {type:XDC file:1 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_0_dout[6]}]
set_property src_info {type:XDC file:1 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_0_dout[14]}]
set_property src_info {type:XDC file:1 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_0_dout[7]}]
set_property src_info {type:XDC file:1 line:378 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_0_dout[8]}]
set_property src_info {type:XDC file:1 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_0_dout[9]}]
set_property src_info {type:XDC file:1 line:380 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_0_dout[15]}]
set_property src_info {type:XDC file:1 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_0_dout[10]}]
set_property src_info {type:XDC file:1 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_0_dout[11]}]
set_property src_info {type:XDC file:1 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_0_dout[12]}]
set_property src_info {type:XDC file:1 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_0_dout[13]}]
set_property src_info {type:XDC file:1 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_2_dout[4]}]
set_property src_info {type:XDC file:1 line:386 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_2_dout[3]}]
set_property src_info {type:XDC file:1 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_2_dout[5]}]
set_property src_info {type:XDC file:1 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_2_dout[6]}]
set_property src_info {type:XDC file:1 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_2_dout[7]}]
set_property src_info {type:XDC file:1 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_2_dout[14]}]
set_property src_info {type:XDC file:1 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_2_dout[15]}]
set_property src_info {type:XDC file:1 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_2_dout[8]}]
set_property src_info {type:XDC file:1 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_2_dout[9]}]
set_property src_info {type:XDC file:1 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_2_dout[10]}]
set_property src_info {type:XDC file:1 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_2_dout[11]}]
set_property src_info {type:XDC file:1 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_2_dout[12]}]
set_property src_info {type:XDC file:1 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_2_dout[13]}]
set_property src_info {type:XDC file:1 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_2_dout[0]}]
set_property src_info {type:XDC file:1 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_2_dout[1]}]
set_property src_info {type:XDC file:1 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {HMBcal_2TCsBD_i/xlconcat_2_dout[2]}]
set_property src_info {type:XDC file:1 line:403 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/cnt_fifo[0]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/cnt_fifo[1]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/cnt_fifo[2]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/cnt_fifo[3]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/cnt_fifo[4]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/cnt_fifo[5]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/cnt_fifo[6]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/cnt_fifo[7]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/cnt_fifo[8]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/FIFOMANAGER/cnt_fifo[9]}]]
set_property src_info {type:XDC file:1 line:404 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/TC_RDAD_WL_SS/A_CH0_intl[0]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/TC_RDAD_WL_SS/A_CH0_intl[1]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/TC_RDAD_WL_SS/A_CH0_intl[2]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/TC_RDAD_WL_SS/A_CH0_intl[3]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/TC_RDAD_WL_SS/A_CH0_intl[4]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/TC_RDAD_WL_SS/A_CH0_intl[5]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/TC_RDAD_WL_SS/A_CH0_intl[6]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/TC_RDAD_WL_SS/A_CH0_intl[7]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/TC_RDAD_WL_SS/A_CH0_intl[8]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/TC_RDAD_WL_SS/A_CH0_intl[9]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/TC_RDAD_WL_SS/A_CH0_intl[10]} {HMBcal_2TCsBD_i/TwoTARGET_C_TopLevel_0/U0/TC_RDAD_WL_SS/A_CH0_intl[11]}]]
